import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import SessionProvider from "./components/SessionProvider";
import Navbar from "./components/Navbar";
import './globals.css';
import "@fortawesome/fontawesome-svg-core/styles.css";
import { NavbarProvider } from "../context/NavbarContext"; // ใช้เส้นทางที่ถูกต้อง
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;
import Toast from './components/Toast';
export const metadata = {
  title: 'LICENSE PLATE',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);  // ใช้ await เพื่อรอการตอบกลับ

  if (!session) {
    console.log("No session found");
  }
  return (
    <html lang="en">
      <body>
        {/* ห่อ SessionProvider รอบเนื้อหาหลัก */}
        <SessionProvider session={session}>
          <NavbarProvider>
            <Navbar /> {/* แสดง Navbar ในทุกหน้า */}
            <Toast/>
            {children}
          </NavbarProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
